language: php
php:
    - 7.3
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
install:
    - travis_retry composer install --no-interaction
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
    - chmod +x php-coveralls.phar
    - php php-coveralls.phar --version
after_success:
    - travis_retry php php-coveralls.phar -v
before_script:
    - mkdir -p build/logs
    - ls -al
script:
    - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
    - ./vendor/bin/psalm
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
